networks:
  backend:
  frontend:


services:
  db:
    image: postgres:18
    container_name: chronos_db_dev
    networks:
    - backend
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .env.dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - chronos_db_dev:/var/lib/postgresql/data
    restart: unless-stopped
  frontend:
    image: chronos_frontend:latest
    container_name: chronos_frontend
    networks:
      - frontend
    restart: unless-stopped